#cloud-config

# wait for an internet connection
bootcmd:
  - until ping -W 1 -c1 8.8.8.8 >/dev/null; do sleep 1; done

package_update: true
package_upgrade: true
disable_root: false

packages: ['figlet']
hostname: "internal"

write_files:
  - path: /etc/bash.bashrc
    permissions: '0755'
    content: !!binary |
      ${host_bashrc}
  - path: /root/.inputrc
    permissions: '0755'
    content: !!binary |
      ${host_inputrc}
  - path: /root/.bash_aliases
    permissions: '0755'
    content: !!binary |
      ${host_aliases}
  - path: /etc/default/motd-news
    owner: root:root
    permissions: '0644'
    content: |
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: "0644"
    content: !!binary |
      ${pamd_sshd_config}
  - path: /etc/ssh/sshd_config
    owner: root:root
    permissions: "0644"
    content: !!binary |
      ${sshd_config}

runcmd:
  - 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'
  - 'echo "deb https://apt.kubernetes.io/ kubernetes-xenial main"  > /etc/apt/sources.list.d/kubernetes.list'
  - 'apt update'
  - 'apt install -y kubectl awscli'
  - 'mkdir -pv /root/.kube/'
  - 'while true; do aws s3 ls s3://${s3_bucket_name}/config > /dev/null; if [ $? -ne 0 ]; then sleep 10; else break; fi; done && aws s3 cp s3://${s3_bucket_name}/config /root/.kube/ && aws s3 rm s3://${s3_bucket_name}/config'

output:
  all: '| tee -a /var/log/cloud-init-output.log'
