#cloud-config

package_update: true
package_upgrade: true
disable_root: 0

packages: ["docker.io", "figlet"]

hostname: "bastion"

runcmd:
  - "systemctl enable docker"
  - "systemctl daemon-reload"
  - "systemctl restart docker"
  - "docker pull ${attack_container_repo}:${attack_container_tag}"
  - "/root/authorized_keys.sh ${github_usernames}"

write_files:
  - path: /etc/bash.bashrc
    permissions: "0755"
    content: !!binary |
      ${bastion_bashrc}
  - path: /root/authorized_keys.sh
    permissions: '0755'
    content: !!binary |
      ${bastion_auth_keys}
  - path: /home/ubuntu/.inputrc
    permissions: "0755"
    content: !!binary |
      ${bastion_inputrc}
  - path: /home/ubuntu/.bash_aliases
    permissions: "0755"
    content: !!binary |
      ${bastion_aliases}
  - path: /home/ubuntu/.bash_login
    permissions: "0755"
    content: |
      export MASTER_IP_ADDRESSES=${master_ip_addresses}
      export NODE_IP_ADDRESSES=${node_ip_addresses}
      export INTERNAL_HOST_IP=${internal_host_private_ip}
      sudo -E docker run -h attack -v /home/ubuntu/progress.json:/progress.json -v /home/ubuntu/tasks.yaml:/tasks.yaml -v /home/ubuntu/challenge.txt:/challenge.txt --net=host -e BASE64_SSH_KEY -e MASTER_IP_ADDRESSES -e NODE_IP_ADDRESSES -e INTERNAL_HOST_IP -it ${attack_container_repo}:${attack_container_tag}
      logout
  - path: /home/ubuntu/progress.json
    permissions: "0666"
    content: "{}"
  - path: /home/ubuntu/challenge.txt
    permissions: "0666"
    content: |
      No scenario instructions found. Have you launched a scenario with 'simulator scenario launch ...'?
  - path: /home/ubuntu/tasks.yaml
    permissions: "0666"
    content: |
      No scenario tasks found. Have you launched a scenario with 'simulator scenario launch ...'?
  - path: /etc/default/motd-news
    owner: root:root
    permissions: "0644"
    content: |
      # Don't call home to canonical
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: "0644"
    content: !!binary |
      ${pamd_sshd_config}
  - path: /etc/ssh/sshd_config
    owner: root:root
    permissions: "0644"
    content: !!binary |
      ${sshd_config}

output:
  all: "| tee -a /var/log/cloud-init-output.log"
